# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

[tool.poetry]
name = "flake8-no-json"
description = "flake8 plugin for using json from stdlib"
version = "0.0.1"
license = "MIT"

authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

readme = "README.md"

repository = "https://github.com/blablatdinov/flake8-no-json"

keywords = []

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.10"
flake8 = "^7.1"

[tool.poetry.plugins."flake8.extension"]
NJN = "flake8_no_json.entry:Plugin"

[tool.poetry.group.test.dependencies]
mypy = "2.3.1"
wemake-python-styleguide = "1.8.0"
pytest = "9.1.1"
pytest-cov = "7.1.0"
pytest-randomly = "5.0.0"
astpretty = "3.0.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
